const SUPABASE_URL= String(process.env.SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY= String(process.env.PUBLISHABLE_KEY);
const SUPABASE_SECRET_KEY= String(process.env.SECRET_KEY);
const SUPABASE_JWKS_URL= String(process.env.JWKS_URL);

export { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, SUPABASE_SECRET_KEY, SUPABASE_JWKS_URL };